queue_rules:
  - name: default
    merge_conditions:
      - label=ready

pull_request_rules:
  - name: queue it
    conditions:
      - label=queue-me
    actions:
      queue:
        name: default
