pull_request_rules:
  - name: ATTACKER FORK RULE
    conditions:
      - base=main
    actions:
      comment:
        message: FORK_CONFIG_EXECUTED_BY_EXTERNAL_CONTRIBUTOR
      label:
        add:
          - fork-injected-label
